### ISSUE TITLE
Deploy to Heroku fails - add-on plan for postgresql:hobby not found

### ISSUE THREAD

**Issue by chadgates** [adaptivdesign/odooku#1]
When pressing deploy to Heroku button, the deploy fails with message: 
"Couldn't find either the add-on service or the add-on plan of "heroku-postgresql:hobby" ... 

Probably need to correct app.json to hold value "hobby-dev" or "hobby-basic" instead of just "hobby".

![voila_capture 2016-08-11_04-54-56_pm](https://cloud.githubusercontent.com/assets/11510951/17592999/aea7e1be-5fe4-11e6-9390-8e0505a849ec.png)

**Comment by adaptivdesign** [comment]
Thanks you're right! Will fix this. There are likely more small issues, because I'm not testing every commit right now. Let me know if you need any help.
