### ISSUE TITLE
force redirect to https ssl

### ISSUE THREAD

**Issue by grauschnabel** [adaptivdesign/odooku#10]
Hi there,

I have configured heroku with my own domain and set up ssl, so now https://myodoo.install works fine.  But now how can I force odoo to redirect to it.

Heroku says: Use the app to check for http and redirect to https
in odoo docs it says use apache or other webserver config for that.

but how can I do it now?

Thanks,
Martin

**Comment by adaptivdesign** [comment]
Will have to look at this, since I'm not running ssl myself at the moment (but I should lol).

**Comment by mgrigajtis** [comment]
I also need to get this working.  For now I do the redirect in JavaScript though the website editor.

**Comment by adaptivdesign** [comment]
I'm currently a little short on time, I can spend some time on Odooku in about a week.

**Comment by mgrigajtis** [comment]
Want some help?

**Comment by adaptivdesign** [comment]
Yes, if anybody wants to contribute to Odooku, feel free to do so. That would be great!

**Comment by grauschnabel** [comment]
I really need that feature now, so where should I start?

**Comment by adaptivdesign** [comment]
This needs to be added to odooku compat. The wsgi application is a good place to start. I ll look at this monday.

**Comment by adaptivdesign** [comment]
I almost have a new feature ready which enables this, plus more. It enables rewriting. A rules.json file should be made in the following format:

```
{
   "http://*": {
     "rewrite": "https://${0}",
     "redirect": true
   "
}
```

I'm running a multi db setup and I name my databases according to the domain. So for example, I have a a db named www_adaptiv_nl for my domain www.adaptiv.nl . Any requests to adaptiv.nl will not match that db. I will fix it like this:

```
{
   "*://adaptiv.nl": {
     "rewrite": "${0}://www.adaptiv.nl",
     "redirect": true
   "
}
```

**Comment by grauschnabel** [comment]
mybe you could provide an example file for that?
Just to know, will this cause 301 permanently moved responses, or which way do you go?
Thanks so much for that work.

**Comment by adaptivdesign** [comment]
Will do. Yes they ll be 301's!

**Comment by adaptivdesign** [comment]
Ok, I have just pushed a new version of odooku-compat. Could you help me test heroku ssl, I can't test this quickly myself now. Instructions:

- Run the wsgi command with `--proxy-mode`
- Create a file in your project root named "rules.json"

```
{
  "http://*": {
    "redirect": "https://{0}"
  }
}
```

If this works I'll make sure to update the docs asap. I'm reworking a lot of stuff.

**Comment by grauschnabel** [comment]
This seems just to work for the root / of the url.  Other urls seem not
to be reloaded.

I would need a rule which redirects everything to https except
`/.well-known/acme-challenge/*
`
How can I do this?

**Comment by adaptivdesign** [comment]
I have made some fixes. Above rule now works, I have tested it with Heroku. Docs will follow.

Regarding your rule exception `/.well-known/acme-challenge/*`, this I cannot support right now. But I assume you want to get a letsencrypt certificate? In that case, heroku now integrates with this service. Just enable automatic certificate management.

**Comment by grauschnabel** [comment]
yes, the thing is that i use flynn and in flynn we have to wait a bit for letsencrypt.  I wrote an odoo module which implements it.  but maybe letsencrypt doesn't check the certificate so this could work....
