### ISSUE TITLE
forked to flynn-odoo

### ISSUE THREAD

**Issue by grauschnabel** [adaptivdesign/odooku#11]
Hi there,

I just wanted to thank you for your work.  It was very easy to fork it and adjust it to flynn (which is like herkou, but you don't pay for it, just for the ec2 instance or the digitalocean package or maybe you use it on you own servers).

Just little adjustments had to be made.  See flynn-odoo and flynn-odoo-buildpack to see the adjustments.

Thanks again,
Martin

**Comment by adaptivdesign** [comment]
Nice work! I'm actually planning on making odooku deploy to more than just heroku. Mayby in the near future we can merge everything together.

**Comment by grauschnabel** [comment]
I would like that! :)
