### ISSUE TITLE
Problem Occures when connecting to S3

### ISSUE THREAD

**Issue by Kalmuraee** [adaptivdesign/odooku#12]
Hello

I've tried deployment on heroku everything went smooth , but a problem occures once it tries to connect to S3.
Here is the details of the deployment : https://gist.github.com/Kalmuraee/1d18791cae618c25f3fc9497dea3771a

Best Regards,

**Comment by Kalmuraee** [comment]
Do I have to specify the region ? in my case it's eu-central-1

**Comment by adaptivdesign** [comment]
Try to create a bucket in eu-west-1 and make sure heroku runs in the european region.. and see what happens. If this is indeed the case, I will fix it.

**Comment by Kalmuraee** [comment]
Yes , It worked ! 
seems it's a region problem

**Comment by Kalmuraee** [comment]
After using the deployment , I don't know the credentials where do i find them ?.

**Comment by Kalmuraee** [comment]
username:admin
password:admin

**Comment by Kalmuraee** [comment]
Still I'm not sure how to install addons and modify on the odoo files .

**Comment by adaptivdesign** [comment]
From now on Odooku can (and should) be configured with AWS_REGION=<your region>. This will also fix your earlier problem.
