### ISSUE TITLE
Installing an addon , modifying the files.

### ISSUE THREAD

**Issue by Kalmuraee** [adaptivdesign/odooku#13]
Hello

I wasn't sure how do I install an addon  and not sure how I modify the files of odoo i.e. css files, template files etc ..
I've tried to look in the documentation but I didn't see anything mentioned , and I've tried to clone the git from heroku but it clones an empty folder .

Best Regards,

**Comment by adaptivdesign** [comment]
Hello, sorry for the late reply. You can simply add your addons under /addons of your repository. They behave exactly the same as in regular Odoo.
