### ISSUE TITLE
AWS_REGION

### ISSUE THREAD

**Issue by grauschnabel** [adaptivdesign/odooku#14]
Hi,

you added AWS_REGION, i just tried to merge that to flynn-odoo, but there is no change in the odooku-buildpack, is that correct?  will the variable be directly used from odoo?

**Comment by adaptivdesign** [comment]
It will be picked up by odooku-compat, no need to change anything in the buildpack.

**Comment by grauschnabel** [comment]
Thats nice, because odooku-compat can be used as is for flynn. :) Although, I didn't test all its features.
