### ISSUE TITLE
port for wkhtmltopdf bug

### ISSUE THREAD

**Issue by grauschnabel** [adaptivdesign/odooku#15]
There is a known bug which prevents odoo with wkhtmltopdf with headers and footers, where headers and footers will not be renderd correctly.

The fix says: set a system variable named 'report.url' with the value "http://127.0.0.1:8069".
What could be the correct value for that variable for odooku?

Thanks,
Martin

**Comment by adaptivdesign** [comment]
just set it to http://myaddress.com

**Comment by grauschnabel** [comment]
works fine, thanks
