### ISSUE TITLE
redirect causes session expiration

### ISSUE THREAD

**Issue by grauschnabel** [adaptivdesign/odooku#16]
Hi,

Since I use the new redirect it causes session expiration on flynn.  Is this the same on heroku?
It just happens if I scale it up to >= 2 workers on my web process.

**Comment by adaptivdesign** [comment]
Are you running redis?

**Comment by grauschnabel** [comment]
Yes, i never had this trouble before, ... Redis works fine.

-- 
Mag. Martin Kaffanke
+43 650 4514224
http://www.kaffanke.at

-----Original Message-----

**Comment by grauschnabel** [comment]
Ok, now I'm not sure anymore if it is redirect or not.. do you have this issue on heroku?

**Comment by adaptivdesign** [comment]
I think I messed something up during the refractor. I'll check it tonight.

**Comment by adaptivdesign** [comment]
Fixed!

**Comment by grauschnabel** [comment]
thanks, works here too!
