### ISSUE TITLE
Note to self

### ISSUE THREAD

**Issue by adaptivdesign** [adaptivdesign/odooku#6]
Make some great docs!

**Comment by mgrigajtis** [comment]
Is there a way to trigger an upgrade?  As in I have installed Odoo through Odooku, and there have since been fixes to the branch, now I need those fixes.  Is there an easy (and safe) way to upgrade?

**Comment by adaptivdesign** [comment]
Yes ofcourse you can! Just trigger a Heroku build. The buildpack will fetch the latest Odoo commit (unless specified otherwise inside odooku.json).
