### ISSUE TITLE
custom addons

### ISSUE THREAD

**Issue by grauschnabel** [adaptivdesign/odooku#8]
Hi there,

You told me in another issue I could put addons in the /addons folder. At the moment I tried to add the ofx import addon so it can work in the community edition, i just copyied 
https://github.com/OCA/bank-statement-import/tree/10.0/account_bank_statement_import_ofx
to `addons/account_bank_statements_import_ofx` in my odooku clone.

But when I deploy that I cannot find the modul in the addons (even not in any developer modus)

So how can I make this work?

I'm just asking here, because I didn't find it in your doks.  I know how valuable time can be, but I hope you can explain this to me little bit.

Thanks,
Martin

**Comment by grauschnabel** [comment]
I just deployed the app one more time, and now, for any unknown reason it is there...  so everything is ok now...

**Comment by adaptivdesign** [comment]
Hey Martin,

No problem for asking! I'm glad you are using Odooku, so just keep on letting me know if you run into problems. 

Regarding your issue, you should be able to put your custom dependencies in requirements.txt. That's the intended place for it. It should not be overwritten.

**Comment by grauschnabel** [comment]
Thanks a lot. Just try to put ofxparser==0.16 in requirements.txt and deploy that. You see heroku installing 0.16, and then removing it and installing 0.15 from odoo_requirements afterwards...

But maybe you could just change the order, make it install odoo_requirements first?

**Comment by adaptivdesign** [comment]
Oh I see, great catch! I will definitely change the order. Also I will bump the versions in the requirement file for as many dependencies as I can.

**Comment by grauschnabel** [comment]
Thats Great, Thanks

**Comment by grauschnabel** [comment]
I have the problem again.   I was just copying the other addons to a new odooku clone, but upstream the addon is not found in the odoo app, even if herku tells me

`remote:        Detected addons directory
`

What am I doing wrong?

**Comment by adaptivdesign** [comment]
Did you manage to get this working?

**Comment by grauschnabel** [comment]
yes I think its about having to enable developer mode in odoo settings and update the /addons directory in the apps menu.  do you aggree?

**Comment by adaptivdesign** [comment]
absolutely.. If you add new addons whilst the database already exists, then you need to do that. It's the same in regular Odoo. Guess we can close this issue :)

**Comment by grauschnabel** [comment]
Yes you can close it, I just wonder if there is a way to install addons by cli rather than this long way over the browser...

**Comment by adaptivdesign** [comment]
Yes you can! Run ```odooku database update --module <your_module>``` . If you run in multi db mode, you have to pass the database name with ```--db-name```. You can run the ```odooku --help``` command for a full list off commands.
